---
title: "02 Explorative analysis and visualisations"
author: "Dominik Klepl"
date: "2/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Single variable exploration

### Availability

We'll start by looking for nonsense values (e.g. availability more than 365)
```{r}
data_clean %>%
  summarise(min = min(availability_365),
            max = max(availability_365))

#there is at least one listing that is never available - let's inspect it more
cat("How many accomodations are never available?",
    data_clean %>% filter(availability_365==0) %>% sdf_nrow())
```

### Minimum nights
```{r}
data_clean %>%
  summarise(min = min(minimum_nights),
            max = max(minimum_nights),
            mean = mean(minimum_nights),
            sd = sd(minimum_nights))

#having minimum nights 999 is obviously ridiculous, let's look at this in more detail
min_nights = data_clean %>% select(minimum_nights) %>% collect()
min_nights$minimum_nights = as.numeric(min_nights$minimum_nights)

ggplot(min_nights, aes(minimum_nights))+
  geom_density()

rm(min_nights)

cat("How many accomodations have minimum nights a year or more?",
    data_clean %>% filter(minimum_nights >= 365) %>% sdf_nrow())

cat("How many accomodations have minimum nights more than mean + 2.5*standard deviation?",
data_clean %>% filter(minimum_nights >= mean(minimum_nights, na.rm = T)+2.5*sd(minimum_nights, na.rm = T)) %>% sdf_nrow())


#let's remove these since they're obviously outliers which would bias the analysis
data_clean = data_clean %>% filter(minimum_nights <= mean(minimum_nights, na.rm = T)+2.5*sd(minimum_nights, na.rm = T))
```
